_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.12.7
        t:
            "1":
                - 55
                - 95
                - 105
            "2":
                - 55
                - 95
                - 105
            "3":
                - 13
                - 23
                - 55
            "4": 3.12.7
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
training_file_id:
    value: file-XMzmEhk3Es71aC4mGVA3Hx
validation_file_id:
    value: file-LPAHgPHATo5R9MyLpYo7cA
